import type { BusinessManager, Client, CreativeAngle, CreativeFormat } from '../types'

/* Static seed: the agency's book of business. Five clients live in the agency's
   own BM; two live on the client's OWN BM (partner access) — exercising both of
   the operator's stated setups. */

export const BUSINESS_MANAGERS: BusinessManager[] = [
  { id: 'bm_agency', name: 'Northbeam Collective (Agency)', type: 'agency', metaBusinessId: '1089423455120031' },
  { id: 'bm_lumiere', name: 'Lumière Beauty (Client BM)', type: 'partner', metaBusinessId: '2284119067430022' },
  { id: 'bm_forge', name: 'Forge Athletics (Client BM)', type: 'partner', metaBusinessId: '3391784550912284' },
]

export const CLIENTS: Client[] = [
  {
    id: 'c_lumiere',
    name: 'Lumière Skincare',
    bmId: 'bm_lumiere',
    vertical: 'Beauty & Skincare',
    accentColor: '#E8A0BF',
    monogram: 'LM',
    status: 'active',
    currency: 'USD',
    monthlyBudget: 180000,
    targetCPA: 32,
    targetROAS: 2.1,
    avgOrderValue: 68,
    contributionMargin: 0.62,
    startDate: '2024-09-02',
  },
  {
    id: 'c_forge',
    name: 'Forge Athletics',
    bmId: 'bm_forge',
    vertical: 'Activewear',
    accentColor: '#5BD1B0',
    monogram: 'FA',
    status: 'active',
    currency: 'USD',
    monthlyBudget: 240000,
    targetCPA: 41,
    targetROAS: 2.3,
    avgOrderValue: 96,
    contributionMargin: 0.55,
    startDate: '2024-06-18',
  },
  {
    id: 'c_hearthwell',
    name: 'Hearthwell Home',
    bmId: 'bm_agency',
    vertical: 'Home & Living',
    accentColor: '#E6B450',
    monogram: 'HW',
    status: 'active',
    currency: 'USD',
    monthlyBudget: 150000,
    targetCPA: 54,
    targetROAS: 2.3,
    avgOrderValue: 122,
    contributionMargin: 0.48,
    startDate: '2024-11-04',
  },
  {
    id: 'c_vela',
    name: 'Vela Supplements',
    bmId: 'bm_agency',
    vertical: 'Health & Supplements',
    accentColor: '#7DA9F7',
    monogram: 'VS',
    status: 'active',
    currency: 'USD',
    monthlyBudget: 130000,
    targetCPA: 27,
    targetROAS: 2.0,
    avgOrderValue: 54,
    contributionMargin: 0.7,
    startDate: '2025-01-13',
  },
  {
    id: 'c_nomad',
    name: 'Nomad Coffee Co.',
    bmId: 'bm_agency',
    vertical: 'Food & Beverage',
    accentColor: '#C98A5E',
    monogram: 'NC',
    status: 'active',
    currency: 'USD',
    monthlyBudget: 88000,
    targetCPA: 24,
    targetROAS: 1.8,
    avgOrderValue: 42,
    contributionMargin: 0.66,
    startDate: '2024-10-21',
  },
  {
    id: 'c_atlas',
    name: 'Atlas Eyewear',
    bmId: 'bm_agency',
    vertical: 'Eyewear & Accessories',
    accentColor: '#9B8AFB',
    monogram: 'AT',
    status: 'active',
    currency: 'USD',
    monthlyBudget: 110000,
    targetCPA: 58,
    targetROAS: 2.55,
    avgOrderValue: 148,
    contributionMargin: 0.6,
    startDate: '2025-02-10',
  },
  {
    id: 'c_bloom',
    name: 'Bloom & Branch',
    bmId: 'bm_agency',
    vertical: 'Plants & Garden',
    accentColor: '#6FCF97',
    monogram: 'BB',
    status: 'onboarding',
    currency: 'USD',
    monthlyBudget: 64000,
    targetCPA: 38,
    targetROAS: 2.1,
    avgOrderValue: 79,
    contributionMargin: 0.58,
    startDate: '2025-05-05',
  },
]

export const CREATIVE_ANGLES: CreativeAngle[] = [
  'UGC Testimonial',
  'Founder Story',
  'Problem / Solution',
  'Product Demo',
  'Offer / Promo',
  'Social Proof',
  'Unboxing',
  'Before / After',
  'Educational',
  'Lifestyle',
]

export const CREATIVE_FORMATS: CreativeFormat[] = ['video', 'image', 'carousel']

/** gradient stops per angle for placeholder thumbnails (demo has no real assets) */
export const ANGLE_GRADIENTS: Record<CreativeAngle, [string, string]> = {
  'UGC Testimonial': ['#6D5BF7', '#36D6C3'],
  'Founder Story': ['#F78DA7', '#7A5CF0'],
  'Problem / Solution': ['#F2994A', '#EB5757'],
  'Product Demo': ['#2D9CDB', '#56CCF2'],
  'Offer / Promo': ['#EB5757', '#F2C94C'],
  'Social Proof': ['#27AE60', '#6FCF97'],
  Unboxing: ['#BB6BD9', '#5BD1B0'],
  'Before / After': ['#2F80ED', '#9B51E0'],
  Educational: ['#11998E', '#38EF7D'],
  Lifestyle: ['#FC5C7D', '#6A82FB'],
}

export const HEADLINE_POOL: Record<CreativeAngle, string[]> = {
  'UGC Testimonial': ['"I can\'t believe the difference"', '"Three weeks in and obsessed"', 'Real results, real people'],
  'Founder Story': ['Why we started this', 'Built by people who needed it', 'Our promise to you'],
  'Problem / Solution': ['Tired of the same problem?', 'There\'s a better way', 'Finally, a fix that works'],
  'Product Demo': ['See it in action', 'How it actually works', 'Watch the magic happen'],
  'Offer / Promo': ['30% off ends Sunday', 'Your first order, on us', 'Limited drop — going fast'],
  'Social Proof': ['Join 200,000+ happy customers', 'The internet\'s favorite', 'As seen everywhere'],
  Unboxing: ['Unboxing the hype', 'What\'s inside?', 'The full experience'],
  'Before / After': ['The 30-day transformation', 'Before vs after', 'Proof it works'],
  Educational: ['The science, simplified', '3 things you didn\'t know', 'What the experts won\'t tell you'],
  Lifestyle: ['Made for your everyday', 'Live a little better', 'The upgrade you deserve'],
}

export const AUDIENCE_LABELS = {
  broad: ['Broad 18–65', 'Broad US — All', 'Advantage+ Broad'],
  interest: ['Interest: Category', 'Interest: Competitors', 'Interest: Enthusiasts'],
  lookalike: ['LLA 1% Purchasers', 'LLA 3% ATC', 'LLA 2% Site Visitors'],
  retargeting: ['RT: 30d Site', 'RT: ATC 14d', 'RT: IG/FB Engagers 90d'],
  advantage: ['Advantage+ Audience', 'Advantage+ Shopping'],
} as const
